# Generated by Django 4.0.5 on 2022-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(max_length=3000)),
                ('imagen', models.URLField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name_plural': 'Avatar'},
        ),
        migrations.AlterModelOptions(
            name='cursos_dictados',
            options={'verbose_name_plural': 'Cursos Dictados'},
        ),
        migrations.AlterModelOptions(
            name='workshops',
            options={'verbose_name_plural': 'Workshops'},
        ),
    ]
