# Generated by Django 4.0.5 on 2022-07-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_posteo_alter_avatar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
