# Generated by Django 4.0.5 on 2022-07-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_posteo_autor_alter_posteo_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
